version: '3'

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka:
        image: confluentinc/cp-kafka:latest
        depends_on:
            - zookeeper
        ports:
            - 9092:9092
            - 9093:9093
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    cassandra:
        image: cassandra
        ports:
            - 7000:7000
            - 9042:9042
        volumes:
            - ./cassandra:/var/lib/cassandra
        environment:
            CASSANDRA_CLUSTER_NAME: chat

    influx:
        image: influxdb
        ports:
            - 8083:8083
            - 8086:8086
        volumes:
            - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
            - ./influx-data:/var/lib/influxdb
        environment:
            INFLUXDB_ADMIN_ENABLED: "true"

    grafana:
        image: grafana/grafana
        ports:
            - 3000:3000
        volumes:
            - ./grafana/:/etc/grafana/provisioning/
        environment:
            GF_SECURITY_ADMIN_PASSWORD: admin

    iris:
        image: jonasrichard/iris:0.0.2
        ports:
            - 8080
              #entrypoint: /srv/iris.sh
        environment:
            OTHER_NODE: ${OTHER_NODE}

